export const TEMPLATE_1_SKELETON = `[FIRST_NAME] [LAST_NAME]
[CITY], [STATE] | Phone: [PHONE] | Email: [EMAIL] | LinkedIn: [LINKEDIN]

PROFESSIONAL SUMMARY
[PROFESSIONAL_SUMMARY_PARAGRAPH]

EDUCATION
[DEGREE] - [FIELD_OF_STUDY]
[UNIVERSITY_NAME] | [START_YEAR] - [END_YEAR]
- [EDUCATION_ACHIEVEMENT_1]
- [EDUCATION_ACHIEVEMENT_2]

PROFESSIONAL EXPERIENCE
[JOB_TITLE_1]
[COMPANY_NAME_1] | [LOCATION_1] | [START_DATE_1] - [END_DATE_1]
- [RESPONSIBILITY_1]
- [RESPONSIBILITY_2]
- [RESPONSIBILITY_3]
- [RESPONSIBILITY_4]

[JOB_TITLE_2]
[COMPANY_NAME_2] | [LOCATION_2] | [START_DATE_2] - [END_DATE_2]
- [RESPONSIBILITY_1]
- [RESPONSIBILITY_2]
- [RESPONSIBILITY_3]

TECHNICAL SKILLS
[SKILL_CATEGORY_1]: [SKILLS_LIST_1]
[SKILL_CATEGORY_2]: [SKILLS_LIST_2]
[SKILL_CATEGORY_3]: [SKILLS_LIST_3]

VOLUNTEERING & MEMBERSHIPS
- [VOLUNTEER_ROLE_1] - [ORGANIZATION_1] | [YEAR_1]
- [VOLUNTEER_ROLE_2] - [ORGANIZATION_2] | [YEAR_2]`

export const TEMPLATE_2_SKELETON = `[FIRST_NAME] [LAST_NAME]
[CITY], [STATE] | Phone: [PHONE] | Email: [EMAIL] | LinkedIn: [LINKEDIN]

PROFESSIONAL PROFILE
[PROFESSIONAL_PROFILE_PARAGRAPH]

KEY CAPABILITIES
- [CAPABILITY_1]: [CAPABILITY_1_DESCRIPTION]
- [CAPABILITY_2]: [CAPABILITY_2_DESCRIPTION]
- [CAPABILITY_3]: [CAPABILITY_3_DESCRIPTION]
- [CAPABILITY_4]: [CAPABILITY_4_DESCRIPTION]

CAREER SUMMARY
([JOB_TITLE_1]) - [COMPANY_NAME_1] | [LOCATION_1] | [START_YEAR_1] - [END_YEAR_1]
([JOB_TITLE_2]) - [COMPANY_NAME_2] | [LOCATION_2] | [START_YEAR_2] - [END_YEAR_2]

QUALIFICATION
- [DEGREE]

PROFESSIONAL DEVELOPMENT
- [CERTIFICATION_1] | [ISSUING_ORG_1] | [YEAR_1]
- [CERTIFICATION_2] | [ISSUING_ORG_2] | [YEAR_2]

RECENT PROFESSIONAL EXPERIENCE
([JOB_TITLE_MAIN])
[COMPANY_NAME_MAIN] | [LOCATION_MAIN] | [START_DATE_MAIN] - [END_DATE_MAIN]
- [COMPREHENSIVE_RESPONSIBILITY_1]
- [ACHIEVEMENT_WITH_CONTEXT_1]
- [PROBLEM_RESOLUTION_1]
- [PROCESS_IMPROVEMENT_1]
- [STAKEHOLDER_COMMUNICATION_1]
- [TECHNICAL_COMPETENCY_1]
- [ADDITIONAL_RESPONSIBILITY_1]
- [ADDITIONAL_RESPONSIBILITY_2]

REFERENCES
Available upon request`

export function getTemplateSkeleton(templateId: string): string {
  return templateId === 'template_1' ? TEMPLATE_1_SKELETON : TEMPLATE_2_SKELETON
}